name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: |
          pacman -Syyu --noconfirm base-devel sudo bash-completion nano git gnupg
          useradd -m builder
          echo 'builder ALL=NOPASSWD: ALL' >> /etc/sudoers
          chown -R builder:builder .
      - name: Build
        run: |
          sudo -u builder bash -c 'source PKGBUILD; for x in ${validpgpkeys[@]}; do gpg --recv-keys $x; done'
          sudo -u builder bash -c 'yes | makepkg -s'
      - name: Pack
        run: |
          mkdir -p /tmp/repo/x86_64
          mv *.pkg.tar.zst /tmp/repo/x86_64
          cd /tmp/repo/x86_64
          repo-add openresty.db.tar.zst *.pkg.tar.zst
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: /tmp/repo
  deploy:
    needs: build
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
